destination  = input("Destination : ")
days         = int(input("days : "))
budget       = float(input("budget : "))
travel_style = input("Style : ")
currency     = input("Currency : ")
travel_month = input("Month of Travel : ")

print("=======================")
print("KelanaAI")
print("=======================")
print(f"Destination     : {destination}")
print(f"Days            : {days}")
print(f"Budget          : {budget}")
print(f"Style           : {travel_style}")
print(f"Currency        : {currency}")
print(f"Month of Travel : {travel_month}")